### ISSUE TITLE
Not working on Internet Explorer !

### ISSUE THREAD

**Issue by pastinepolenta** [ronik-design/postcss-object-fit-images#11]
The plugin adds the font-family trick rule but that is not enough to make Explorer working properly:

see: https://codepen.io/stilllife00/full/jLZVVb/
The image is not "cover" is just stretched

**Comment by fregante** [comment]
From the readme:

> For use with [object-fit-images](https://github.com/bfred-it/object-fit-images)

You'll also need to load that JS file in the browser to enable the behavior.
