### ISSUE TITLE
Generated styles don't inherit styles

### ISSUE THREAD

**Issue by missmatsuko** [ronik-design/postcss-object-fit-images#13]
Not sure if it's even possible to fix this, but I didn't see it addressed yet.

I came across it when I wanted to change the `object-position` of an element in a media query, but inherit the `object-fit` style from outside the media query. 

Here's a simpler example of the issue:

**Source CSS**
```
.cover {
    object-fit: cover;
}

.cover.center {
    object-position: center;
}
```

**Expected generated font-family styles**
```
.cover {
    font-family: "object-fit: cover;";
}

.cover.center {
    font-family: "object-fit: cover; object-position: center;";
}
```

**Actual generated font-family styles**
```
.cover {
    font-family: "object-fit: cover;";
}

.cover.center {
    /* nothing */
}
```

**Workaround**
I *can* get around it by duplicating the `object-fit` style for the element that should be inheriting it. However, this means that I still need to manually modify my CSS to suit the object-fit-images polyfill.
```
.cover {
    object-fit: cover;
}

.cover.center {
    object-fit: cover;
    object-position: center;
}
```

**Comment by fregante** [comment]
Yes that's a limitation given that the two properties are merged into one, `font-family`, so when one exists it will override the previous one in full. Can't be fixed
