### ISSUE TITLE
node 0.12 support

### ISSUE THREAD

**Issue by mshick** [ronik-design/postcss-object-fit-images#3]
@bfred-it how do you feel about support for node 0.12? With a LTS release of node 4, I'm disinclined to lock projects into those restrictions and complications (incorporating babel if I want to use a modern syntax).

I'll follow your lead though, since this module just accompanies your work.

FWIW, I would just need to change some `const`s and `let`s to `var`. Would take no more than a few minutes.

**Comment by fregante** [comment]
Sure, why not. The change was minimal and I was able to do it on my phone while in line 😂
