### ISSUE TITLE
Doesn't support multiple font- declarations.

### ISSUE THREAD

**Issue by ReDrUm** [ronik-design/postcss-object-fit-images#6]
The conversion seems to break when supplying multiple/separate `font-` rules. e.g.

```
.foo {
    font-family: "Open Sans", sans-serif;
    font-weight: bold;
    object-fit: cover;
}
```

Becomes:

```
.foo {
    font-family: "Open Sans", sans-serif;
    font-family: "object-fit:cover", bold;
    -o-object-fit: cover;
    object-fit: cover;
}
```

Instead of the expected:

```
.foo {
    font-family: "object-fit:cover", "Open Sans", sans-serif;
    font-weight: bold;
    -o-object-fit: cover;
    object-fit: cover;
}
```

It seems to maintain the last `font-` declaration and treat it as `font-family` instead of actually looking for `font-family`.

**Comment by fregante** [comment]
Thank you for your report! It might be because of this line:

https://github.com/ronik-design/postcss-object-fit-images/blob/master/index.js#L31

The regex should be `/^font(-family)?$/`

Can you make this test locally to see if that fixes it for you?

**Comment by ReDrUm** [comment]
Yes that solves it thanks :) I've created #7 for it.

**Comment by fregante** [comment]
@mshick can you push this version to npm?
