### ISSUE TITLE
Update urls on package.json

### ISSUE THREAD

**Issue by shri3k** [ronik-design/postcss-object-fit-images#8]
Hello, 
I think the urls in `package.json` for this repo needs to be updated as it's currently pointing to `<username>/postcss-object-fit-images` rather than `<org_name>/postcss-object-fit-images`. 
Currently npm page is pointing to github's 404 page.

Thank you.

**Comment by fregante** [comment]
Thank you for the report! Do you want to send a PR?

**Comment by shri3k** [comment]
Done. Might need to bump up the patch version before pushing to `npm` though.
